### ISSUE TITLE
Error importing energy.py / ModuleNotFoundError

### ISSUE THREAD

**Issue by Tenkc** [nielsfaber/zoned-heating#2]
Another user here ;). Or at least wanne-be user, I'm trying to get this to work, but it doesn't.

Setup: Honeywell T6 thermostat connected to HA (2022.9.6) through Homekit integration in the living room, Popp TRV in the office.

Error in the log:

ERROR (MainThread) [homeassistant.helpers.integration_platform] Unexpected error importing zoned_heating/energy.py
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/integration_platform.py", line 40, in _async_process_single_integration_platform_component
    platform = integration.get_platform(platform_name)
  File "/usr/src/homeassistant/homeassistant/loader.py", line 681, in get_platform
    cache[full_name] = self._import_platform(platform_name)
  File "/usr/src/homeassistant/homeassistant/loader.py", line 698, in _import_platform
    return importlib.import_module(f"{self.pkg_path}.{platform_name}")
  File "/usr/local/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1004, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'custom_components.zoned-heating.energy'

**Comment by nielsfaber** [comment]
For some reason your HA instance expects the zoned-heating integration to expose some functions related to the energy dashboard of HA.
I am personally not using the energy dashboard, I also wonder why/how using it would cause such error. 
This component doesn't use any functionality of it.
I will ask the developers of HA on Discord, let's see if they know what's going on.

**Comment by nielsfaber** [comment]
Unfortunately I didn't get any useful pointers from the Discord forums.
I have no idea how to help with this issue.

**Comment by Tenkc** [comment]
Too bad, but thanks for the help!

**Comment by Tenkc** [comment]
Apparently something has changed, because it is working now (tested with HA version 2023.2.4) :).

**Comment by nielsfaber** [comment]
Thanks for letting me know!
Nothing changed on my side, so apparently something got fixed in HA.
